[versions]
activityCompose = "1.13.0"
appcompat = "1.7.1"
composeBom = "2026.05.01"
constraintlayoutCompose = "1.1.1"
coreKtx = "1.18.0"
coreSplashscreen = "1.2.0"
datastorePreferences = "1.2.1"
espressoCore = "3.7.0"
androidXJUnit = "1.3.0"
koin = "4.2.1"
koinCompose = "4.2.1"
androidGradlePlugin = "9.2.0-alpha01"
kotlin = "2.3.21"
kotlinxCoroutinesAndroid = "1.11.0"
kotlinxDatetime = "0.8.0"
ksp = "2.3.9"
material = "1.13.0"
navigationCompose = "2.9.8"
room = "2.8.4"
junit = "4.13.2"
kotlinter = "5.5.0"
kover = "0.9.8"
aboutLicenses = "15.0.3"
androidLifecycle = "2.10.0"
browser = "1.10.0"
ktoml = "0.7.1"
konfetti = "2.0.5"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidXJUnit" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidLifecycle" }
androidx-lifecycle-runtimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidLifecycle" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
koin = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koinCompose" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
material = { module = "com.google.android.material:material", version.ref = "material" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
aboutlicenses-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLicenses" }
ktoml = { module = "com.akuleshov7:ktoml-core", version.ref = "ktoml" }
konfetti = { module = "nl.dionsegijn:konfetti-compose", version.ref = "konfetti" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
aboutlicenses = { id ="com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLicenses" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }

