package app.ministrylogbook.ui.theme

import androidx.compose.ui.graphics.Color

val ThemeLightWarning = Color(0xfffacc15)
val ThemeLightOnWarning = Color(0xff854d0e)
val ThemeLightOutgoingTransfer = Color(0xFFD1D3D9)
val ThemeLightOnOutgoingTransfer = Color(0xFF272a2e)

val md_theme_light_primary = Color(0xFF00658c)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFc3e7ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001e2d)
val md_theme_light_secondary = Color(0xFF4e616d)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd1e5f4)
val md_theme_light_onSecondaryContainer = Color(0xFF0a1e28)
val md_theme_light_tertiary = Color(0xFF615a7c)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFe8deff)
val md_theme_light_onTertiaryContainer = Color(0xFF1d1735)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfcff)
val md_theme_light_onBackground = Color(0xFF191c1e)
val md_theme_light_surface = Color(0xFFfbfcff)
val md_theme_light_onSurface = Color(0xFF191c1e)
val md_theme_light_surfaceVariant = Color(0xFFdde3ea)
val md_theme_light_onSurfaceVariant = Color(0xFF41484d)
val md_theme_light_outline = Color(0xFF71787e)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1f4)
val md_theme_light_inverseSurface = Color(0xFF2e3133)
val md_theme_light_inversePrimary = Color(0xFF79d0ff)

val ThemeDarkWarning = Color(0xff854d0e)
val ThemeDarkOnWarning = Color(0xfffde047)
val ThemeDarkOutgoingTransfer = Color(0xFF404047)
val ThemeDarkOnOutgoingTransfer = Color(0xFFCAD3DB)

val md_theme_dark_primary = Color(0xFF79d0ff)
val md_theme_dark_onPrimary = Color(0xFF00344a)
val md_theme_dark_primaryContainer = Color(0xFF004c6a)
val md_theme_dark_onPrimaryContainer = Color(0xFFc3e7ff)
val md_theme_dark_secondary = Color(0xFFb6c9d8)
val md_theme_dark_onSecondary = Color(0xFF21333e)
val md_theme_dark_secondaryContainer = Color(0xFF374955)
val md_theme_dark_onSecondaryContainer = Color(0xFFd1e5f4)
val md_theme_dark_tertiary = Color(0xFFcbc1ea)
val md_theme_dark_onTertiary = Color(0xFF322c4b)
val md_theme_dark_tertiaryContainer = Color(0xFF494264)
val md_theme_dark_onTertiaryContainer = Color(0xFFe8deff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1e)
val md_theme_dark_onBackground = Color(0xFFe1e2e5)
val md_theme_dark_surface = Color(0xFF191c1e)
val md_theme_dark_onSurface = Color(0xFFe1e2e5)
val md_theme_dark_surfaceVariant = Color(0xFF41484d)
val md_theme_dark_onSurfaceVariant = Color(0xFFc0c7cd)
val md_theme_dark_outline = Color(0xFF8b9298)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1e)
val md_theme_dark_inverseSurface = Color(0xFFe1e2e5)
val md_theme_dark_inversePrimary = Color(0xFF00658c)

val ProgressPositive = Color(0xFF4FB782)
val ProgressNegative = Color(0xFFEA7625)
