name: Release

on:
  push:
    tags: [ "*" ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/MinistryLogbook.jks'
          fileDir: ${{ github.workspace }}
          encodedString: ${{ secrets.KEYSTORE }}

      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: build prod
        run: ./gradlew app:bundleRelease app:assembleDebug app:assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Create a Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          prerelease: ${{ contains(github.ref_name, 'beta') }}
          files: |
            ./app/build/outputs/bundle/release/app-release.aab
            ./app/build/outputs/apk/release/app-release.apk
            ./app/build/outputs/apk/debug/app-debug.apk
