name: Release

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --tags

      - name: Decode Keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/MinistryLogbook.jks'
          fileDir: ${{ github.workspace }}
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: build prod
        run: ./gradlew app:bundleRelease app:assembleDebug app:assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Create a Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref_name, 'beta') }}
          files: |
            ./app/build/outputs/bundle/release/app-release.aab
            ./app/build/outputs/mapping/release/*.txt
            ./app/build/outputs/apk/release/app-release.apk
            ./app/build/outputs/apk/debug/app-debug.apk
